package com.example.chat.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Data Transfer Object (DTO) for chat messages.
 *
 * This class represents a chat message in responses to clients.
 * It includes all message information including the database-generated
 * ID and timestamp.
 *
 * Used for:
 * - Returning messages from REST API endpoints
 * - Broadcasting messages through WebSocket
 * - RabbitMQ message payloads
 *
 * Lombok annotations provide:
 * - @Data: Generates getters, setters, toString, equals, and hashCode
 * - @NoArgsConstructor: Generates no-argument constructor (required for deserialization)
 * - @AllArgsConstructor: Generates constructor with all fields
 *
 * @author Chat Application Team
 * @version 1.0.0
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class MessageDto {

    /**
     * Unique identifier of the message.
     * Auto-generated by the database.
     */
    private Long id;

    /**
     * Username of the message sender.
     * Maximum length is 100 characters.
     */
    private String username;

    /**
     * Content/text of the message.
     * Maximum length is 1000 characters.
     */
    private String content;

    /**
     * Name of the chat room where the message belongs.
     * Can be null for messages in the general/public room.
     * Maximum length is 50 characters.
     */
    private String roomName;

    /**
     * Timestamp when the message was created.
     * Automatically set when the message is persisted to the database.
     */
    private LocalDateTime createdAt;
}
