version: '3.8'

# Development overrides for podman-compose.yml
# Use with: podman-compose -f podman-compose.yml -f podman-compose.dev.yml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    environment:
      FLASK_DEBUG: "True"
    volumes:
      - .:/app
    command: python app.py
